# Generated by Django 3.2.5 on 2022-05-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
