# Generated by Django 3.2.5 on 2022-05-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_notes_pdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
