# Generated by Django 3.2.5 on 2022-05-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_alter_note_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pdf',
            field=models.FileField(null=True, upload_to='static/pdf/'),
        ),
    ]
