# Generated by Django 3.2.5 on 2022-05-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quepaper', '0002_auto_20220513_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thirdsem2',
            new_name='FirstYear',
        ),
        migrations.RenameModel(
            old_name='Thirdsem1',
            new_name='SecondYear',
        ),
        migrations.RenameModel(
            old_name='Firstsem1',
            new_name='ThirdYear',
        ),
        migrations.DeleteModel(
            name='Firstsem2',
        ),
        migrations.DeleteModel(
            name='Secondsem1',
        ),
        migrations.DeleteModel(
            name='Secondsem2',
        ),
    ]
