# Generated by Django 3.2.5 on 2022-05-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quepaper', '0003_auto_20220527_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstYear',
        ),
        migrations.DeleteModel(
            name='SecondYear',
        ),
        migrations.DeleteModel(
            name='ThirdYear',
        ),
    ]
