# Generated by Django 3.2.5 on 2022-05-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quepaper', '0004_auto_20220530_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='static/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='sem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='static/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='sem3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='static/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='sem4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='static/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='sem5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='static/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='sem6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='static/pdf/')),
            ],
        ),
    ]
