# Generated by Django 3.2.5 on 2022-05-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADBMS_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('date', models.DateField()),
                ('attendance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AI_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('date', models.DateField()),
                ('attendance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MC_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('date', models.DateField()),
                ('attendance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PHP_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('date', models.DateField()),
                ('attendance', models.BooleanField()),
            ],
        ),
    ]
