# Generated by Django 3.2.5 on 2022-05-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbms_attendance',
            name='stu_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ai_attendance',
            name='stu_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mc_attendance',
            name='stu_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='php_attendance',
            name='stu_id',
            field=models.IntegerField(null=True),
        ),
    ]
