# Generated by Django 3.2.5 on 2022-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_auto_20220515_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbms_attendance',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ai_attendance',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mc_attendance',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='php_attendance',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
