# Generated by Django 3.2.5 on 2022-05-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_auto_20220516_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbms_attendance',
            name='attendance',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ai_attendance',
            name='attendance',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mc_attendance',
            name='attendance',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='php_attendance',
            name='attendance',
            field=models.BooleanField(null=True),
        ),
    ]
