# Generated by Django 3.2.5 on 2022-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_auto_20220516_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbms_attendance',
            name='sem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ai_attendance',
            name='sem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mc_attendance',
            name='sem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='php_attendance',
            name='sem',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
