# Generated by Django 3.2.5 on 2022-05-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_auto_20220516_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGMA_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('attendance', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(null=True)),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField(null=True)),
                ('sem', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ADBMS_Attendance',
        ),
        migrations.RemoveField(
            model_name='ai_attendance',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='ai_attendance',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='ai_attendance',
            name='stu_id',
        ),
        migrations.RemoveField(
            model_name='mc_attendance',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='mc_attendance',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='mc_attendance',
            name='stu_id',
        ),
        migrations.RemoveField(
            model_name='php_attendance',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='php_attendance',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='php_attendance',
            name='stu_id',
        ),
    ]
