# Generated by Django 3.2.5 on 2022-06-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0007_auto_20220520_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_attendance',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cgma_attendance',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mc_attendance',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='php_attendance',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='roll_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
